# -*- coding: utf-8 -*-
"""Intent Classification Using DistillBert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIehBDBikULnzb92lGhTREUL5Vo-KSLh
"""

import zipfile
import os

zip_path = "/content/Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv.zip"
extract_path = "/content/extracted_zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print(os.listdir(extract_path))

import pandas as pd
folder_path = "/content/extracted_zip"

files = os.listdir(folder_path)
print(files)

df = pd.read_csv(os.path.join(folder_path, "Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv"))

df.head()

df.shape

df.info()

df.columns

import re
import string
import nltk

nltk.download('stopwords')
nltk.download('wordnet')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

"""Checking Duplicates in Different **Aspects**"""

duplicates = df[df.duplicated()]
print(duplicates.head())

print(df["instruction"].duplicated().sum())

duplicate_instructions = df[df["instruction"].duplicated(keep=False)]

duplicate_instructions.sort_values("instruction").head(20)

conflicts = (
    df.groupby("instruction")["intent"]
      .nunique()
      .reset_index()
)

conflicts = conflicts[conflicts["intent"] > 1]

print(conflicts.head())

df[df["instruction"].isin(conflicts["instruction"])]

# Duplicate Instruction-Intent Pairs.

duplicates = df.duplicated(
    subset=["instruction","intent"]
)

print(duplicates.sum())

duplicate_pairs = df[
    df.duplicated(
        subset=["instruction", "intent"],
        keep=False
    )
]

print("Number of duplicate instruction-intent pairs:",
      len(duplicate_pairs))

duplicate_pairs.sort_values(
    ["instruction", "intent"]
).head(20)

# Same instruction but different intents.

conflicts = (
    df.groupby("instruction")["intent"]
      .nunique()
      .reset_index()
)

conflicts = conflicts[
    conflicts["intent"] > 1
]

print(conflicts.head())

df[
    df["instruction"].isin(
        conflicts["instruction"]
    )
].sort_values("instruction")

# Removing Intent - instruction pairs.

intent_df = (
    df[["instruction", "intent"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Original rows:", len(df))
print("Intent dataframe rows:", len(intent_df))

intent_df.head(10)

intent_df["intent"].value_counts()

"""Visualizes the intent Distribution"""

import matplotlib.pyplot as plt
intent_df["intent"].value_counts().plot(
    kind = "bar"
)
plt.show()

# Checking Number of classes.



intent_df["intent"].nunique()

sorted(intent_df["intent"].unique())

"""Checking text length distribution which is very important for choosing max_length."""

intent_df["num_words"] = (
    intent_df["instruction"]
    .str.split()
    .str.len()
)

intent_df["num_words"].describe()

intent_df["num_words"].hist(
    bins=30
)

"""Check Placeholder frequency"""

import re

placeholders = set()

for text in intent_df["instruction"]:

  found = re.findall(
      r"\{\{.*?\}\}", text
  )

  placeholders.update(found)

print(placeholders)

placeholders_map = {"{{Account Type}}": "<Account Type>", "{{Invoice Number}}":"<Invoice Number>", "{{Currency Symbol}}":"<Currency Symbol>", "{{Person Name}}":"<Person Name>",
                    "{{Delivery City}}":"<Delivery City>", "{{Account Category}}":"<Account Category>", "{{Delivery Country}}":"<Delivery Country>", "{{Refund Amount}}":"<Refund Amount>",
                    "{{Order Number}}":"<Order Number>"}

intent_df["instruction"] = intent_df["instruction"].replace(
    placeholders_map,
    regex=True
)

import re

remaining = intent_df["instruction"].str.contains(
    r"\{\{.*?\}\}",
    regex=True
).sum()

print("Remaining placeholders:", remaining)

"""Check Label Noise"""

conflicts = (
    intent_df.groupby("instruction")["intent"].nunique()
)
conflicts = conflicts[
    conflicts > 1
]
print(conflicts)

"""Encode labels"""

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

intent_df["label"] = encoder.fit_transform(
    intent_df["intent"]
)

intent_df

!pip install transformers datasets evaluate accelerate

print('Installing torchvision...')
!pip install torchvision
print('torchvision installed.')

"""TRAIN-TEST-SPLIT"""

from sklearn.model_selection import train_test_split

train_df , test_df = train_test_split(
    intent_df,
    test_size = 0.2,
    stratify = intent_df["label"],
    random_state = 42
)

LOAD THE MODEL TOKENIZER

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "distilbert-base-uncased"
)

"""Tokenization Function

How to decide the default parameter Max_length.
"""

token_lengths = intent_df["instruction"].apply(
    lambda x: len(tokenizer.tokenize(x))
)

print("90th percentile:", token_lengths.quantile(0.90))
print("95th percentile:", token_lengths.quantile(0.95))
print("99th percentile:", token_lengths.quantile(0.99))
print("Max:", token_lengths.max())

def tokenize(batch):

    return tokenizer(
        batch["instruction"],
        truncation=True,
        padding="max_length",
        max_length=64
    )

"""Convert to HuggingFace Dataset"""

from datasets import Dataset

train_dataset = Dataset.from_pandas(
    train_df[["instruction","label"]]
)

test_dataset = Dataset.from_pandas(
    test_df[["instruction","label"]]
)

"""Tokenize"""

train_dataset = train_dataset.map(
    tokenize,
    batched=True
)

test_dataset = test_dataset.map(
    tokenize,
    batched=True
)

train_dataset.set_format(
    type="torch",
    columns=[
        "input_ids",
        "attention_mask",
        "label"
    ]
)

test_dataset.set_format(
    type="torch",
    columns=[
        "input_ids",
        "attention_mask",
        "label"
    ]
)

"""To decide the num_labels"""

print(train_df["label"].nunique())

"""LOADING THE MODEL"""

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels= 27
)

"""Metrics Function"""

import numpy as np

from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support
)

def compute_metrics(pred):

    labels = pred.label_ids

    preds = pred.predictions.argmax(-1)

    precision, recall, f1, _ = \
        precision_recall_fscore_support(
            labels,
            preds,
            average="weighted"
        )

    acc = accuracy_score(
        labels,
        preds
    )

    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

"""### TRAINING"""

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir = "./results",

    eval_strategy = "epoch",

    save_strategy = "epoch",

    learning_rate = 2e-5,

    per_device_train_batch_size = 16,

    per_device_eval_batch_size = 16,

    num_train_epochs = 5,

    weight_decay = 0.01,

    logging_steps = 50 ,

    load_best_model_at_end = True ,

    metric_for_best_model = "accuracy"
)

from transformers import Trainer

!pip uninstall -y transformers torchvision torch accelerate

!pip install -q \
torch==2.6.0 \
torchvision==0.21.0 \
transformers==4.51.3 \
accelerate==1.6.0 \
datasets \
evaluate

trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

results = trainer.evaluate()

print(results)

"""Classification Report"""

predictions = trainer.predict(test_dataset)

y_pred = predictions.predictions.argmax(
    axis=1
)

y_true = predictions.label_ids

from sklearn.metrics import classification_report

print(
    classification_report(
        y_true,
        y_pred,
        target_names=encoder.classes_
    )
)

"""Confusion Matrix"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_true,
    y_pred
)

import matplotlib.pyplot as plt

plt.figure(figsize=(7,6))

plt.imshow(cm)

plt.colorbar()

plt.title(
    "Confusion Matrix"
)

plt.show()

"""Training Loss"""

history = trainer.state.log_history

train_loss = []

for log in history:

    if "loss" in log:

        train_loss.append(
            log["loss"]
        )

plt.figure(figsize=(8,5))

plt.plot(train_loss)

plt.xlabel("Steps")

plt.ylabel("Loss")

plt.title(
    "Training Loss"
)

plt.show()

"""Validation Accuracy Graph"""

eval_acc = []

for log in history:

    if "eval_accuracy" in log:

        eval_acc.append(
            log["eval_accuracy"]
        )

plt.figure(figsize=(8,5))

plt.plot(eval_acc)

plt.xlabel("Epoch")

plt.ylabel("Accuracy")

plt.title(
    "Validation Accuracy"
)

plt.show()

"""Model Save"""

model.save_pretrained(
    "intent_classifier"
)

tokenizer.save_pretrained(
    "intent_classifier"
)

"""Test On New Query"""

text = "Please cancel my order"   # The model will giving wrong prediction by this query: I no longer need this item.

inputs = tokenizer(
    text,
    return_tensors="pt",
    truncation=True,
    padding=True
)

device = model.device


inputs = {
    k: v.to(device)
    for k, v in inputs.items()
}

outputs = model(**inputs)

pred = outputs.logits.argmax(
    dim=1
).item()

id2intent = {
    idx: label
    for idx, label in enumerate(encoder.classes_)
}

intent2id = {
    intent: idx
    for idx, intent in enumerate(encoder.classes_)
}

id2intent = {
    idx: intent
    for intent, idx in intent2id.items()
}

print(id2intent[pred])

outputs = model(**inputs)

pred = outputs.logits.argmax(dim=1).item()

print("Predicted Label ID:", pred)
print("Predicted Intent:", id2intent[pred])

# Saving this model to the hugging face.

from google.colab import drive

drive.mount('/content/drive')

model.save_pretrained(
    "/content/drive/MyDrive/ecommerce_chatbot/intent_classifier"
)

tokenizer.save_pretrained(
    "/content/drive/MyDrive/ecommerce_chatbot/intent_classifier"
)

import json

with open("evaluation_results.json", "w") as f:
    json.dump(results, f, indent=4)

"""SAVE OUTPUT REPORT"""

import os

project_dir = "/content/drive/MyDrive/AI_Ecommerce_Chatbot"

os.makedirs(project_dir, exist_ok=True)



"""SAVE MODELS AND TOKENIZERS"""

save_path = f"{project_dir}/intent_classifier"

model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

"""SAVE INTENT MAPPING

> Add blockquote


"""

import json

with open(f"{project_dir}/intent2id.json", "w") as f:
    json.dump(intent2id, f)

with open(f"{project_dir}/id2intent.json", "w") as f:
    json.dump(id2intent, f)

"""Save Evaluation Metrics"""

results = trainer.evaluate()
results

import json

with open(f"{project_dir}/evaluation_results.json", "w") as f:
    json.dump(results, f, indent=4)

"""Save Classification Report"""

from sklearn.metrics import classification_report

report = classification_report(
    y_true,
    y_pred,
    target_names=encoder.classes_
)

with open(
    f"{project_dir}/classification_report.txt",
    "w"
) as f:
    f.write(report)

"""Save Confusion Matrix Figure"""

plt.savefig(
    f"{project_dir}/confusion_matrix.png",
    bbox_inches="tight"
)

"""Save Loss Curve"""

plt.savefig(
    f"{project_dir}/training_loss.png",
    bbox_inches="tight"
)

"""Save Accuracy Curve"""

plt.savefig(
    f"{project_dir}/validation_accuracy.png",
    bbox_inches="tight"
)

"""Save W&B Run"""

import wandb

wandb.init(
    project="ecommerce-intent-classifier"
)

wandb.finish()

# To keep a local copy:

wandb_dir = "./wandb"

import shutil

shutil.copytree(
    wandb_dir,
    f"{project_dir}/wandb_logs",
    dirs_exist_ok=True
)

