# -*- coding: utf-8 -*-
"""Name Entity Recognition using DISTILLBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwOnLDAgP3tmbW7XXmNHZiskfNSn4-2t
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers datasets seqeval accelerate -q

"""LOADING THE DATASET"""

import pickle
with open('/content/drive/MyDrive/unique_dataset.pkl', 'rb') as f:
    unique_dataset = pickle.load(f)

from google.colab import files

files.download('/content/drive/MyDrive/unique_dataset.pkl')

"""COUNTING THE NUMBER OF ENTITY"""

from collections import Counter

entity_counts = Counter()
for _, ann in unique_dataset:
    entity_counts.update(label for _, _, label in ann["entities"])

print(entity_counts)

import pandas as pd

pd.DataFrame(entity_counts.items(), columns=["Entity", "Count"])\
  .sort_values("Count", ascending=False)\
  .reset_index(drop=True)

from sklearn.model_selection import train_test_split

train_data, dev_data = train_test_split(
    unique_dataset,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

"""Create Label Mapping"""

labels = set()

for _, ann in train_data:
    for _, _, label in ann["entities"]:
        labels.add(label)

entity_labels = sorted(labels)

label_list = ["O"]

for label in entity_labels:
    label_list.extend([
        f"B-{label}",
        f"I-{label}"
    ])

label2id = {
    label: idx
    for idx, label in enumerate(label_list)
}

id2label = {
    idx: label
    for label, idx in label2id.items()
}

print(label_list)

"""Convert to Token Classification Format"""

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "distilbert-base-uncased"
)

"""CONVERTING INTO HUGGING FACE FORMAT"""

def convert_to_hf_format(data):

    hf_data = []

    for text, ann in data:

        entities = ann["entities"]

        encoding = tokenizer(
            text,
            return_offsets_mapping=True,
            truncation=True,
            max_length=128
        )

        labels = ["O"] * len(
            encoding["offset_mapping"]
        )

        for start, end, entity in entities:

            first = True

            for idx, (s, e) in enumerate(
                encoding["offset_mapping"]
            ):

                if s >= start and e <= end and s != e:

                    if first:

                        labels[idx] = (
                            f"B-{entity}"
                        )

                        first = False

                    else:

                        labels[idx] = (
                            f"I-{entity}"
                        )

        label_ids = []

        for label in labels:

            label_ids.append(
                label2id[label]
            )

        hf_data.append({

            "text": text,

            "input_ids":
            encoding["input_ids"],

            "attention_mask":
            encoding["attention_mask"],

            "labels":
            label_ids
        })

    return hf_data

"""Convert Dataset"""

train_hf = convert_to_hf_format(
    train_data
)

dev_hf = convert_to_hf_format(
    dev_data
)

"""Create Hugging Face Dataset"""

from datasets import Dataset

train_dataset = Dataset.from_list(
    train_hf
)

dev_dataset = Dataset.from_list(
    dev_hf
)

"""Load DistilBERT"""

from transformers import (
    AutoModelForTokenClassification
)

model = (
    AutoModelForTokenClassification
    .from_pretrained(

        "distilbert-base-uncased",

        num_labels=len(label_list),

        id2label=id2label,

        label2id=label2id
    )
)

"""Data Collator"""

from transformers import (
    DataCollatorForTokenClassification
)

data_collator = (
    DataCollatorForTokenClassification(
        tokenizer
    )
)

"""Metrics"""

!pip install evaluate -q

import evaluate
import numpy as np
seqeval = evaluate.load(
    "seqeval"
)

"""METRIC COMPUTING"""

def compute_metrics(p):

    predictions, labels = p

    predictions = np.argmax(
        predictions,
        axis=2
    )

    true_predictions = []

    true_labels = []

    for pred, label in zip(
        predictions,
        labels
    ):

        pred_labels = []

        true = []

        for p_i, l_i in zip(
            pred,
            label
        ):

            if l_i != -100:

                pred_labels.append(
                    id2label[p_i]
                )

                true.append(
                    id2label[l_i]
                )

        true_predictions.append(
            pred_labels
        )

        true_labels.append(
            true
        )

    results = seqeval.compute(

        predictions=true_predictions,

        references=true_labels
    )

    return {

        "precision":
        results["overall_precision"],

        "recall":
        results["overall_recall"],

        "f1":
        results["overall_f1"],

        "accuracy":
        results["overall_accuracy"]
    }

"""Training Arguments"""

from transformers import (
    TrainingArguments
)

training_args = TrainingArguments(

    output_dir="./distilbert_ner",

    eval_strategy="epoch",

    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=16,

    per_device_eval_batch_size=16,

    num_train_epochs=5,

    weight_decay=0.01,

    logging_steps=50,

    load_best_model_at_end=True,

    metric_for_best_model="f1",

    greater_is_better=True,

    report_to="none"
)

"""TRAINER"""

from transformers import Trainer

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=dev_dataset,

    data_collator=data_collator,

    compute_metrics=compute_metrics
)

trainer.train()

"""Evaluate"""

results = trainer.evaluate()

print(results)

print("Overall Metrics")
print("-" * 50)

print(f"Precision : {results['eval_precision']:.4f}")
print(f"Recall    : {results['eval_recall']:.4f}")
print(f"F1 Score  : {results['eval_f1']:.4f}")
print(f"Accuracy  : {results['eval_accuracy']:.4f}")
print(f"Loss      : {results['eval_loss']:.4f}")

"""Per-Entity Evaluation"""

predictions, labels, _ = trainer.predict(dev_dataset)

"""Convert logits"""

import numpy as np

predictions = np.argmax(predictions, axis=2)

"""Remove ignored tokens:"""

true_predictions = []
true_labels = []

for pred, label in zip(predictions, labels):

    pred_seq = []
    label_seq = []

    for p, l in zip(pred, label):

        if l != -100:

            pred_seq.append(id2label[p])
            label_seq.append(id2label[l])

    true_predictions.append(pred_seq)
    true_labels.append(label_seq)

from seqeval.metrics import classification_report

report = classification_report(
    true_labels,
    true_predictions,
    digits=4,
    output_dict=True
)

trainer.save_model("/content/drive/MyDrive/distilbert_ner_model")
tokenizer.save_pretrained("/content/drive/MyDrive/distilbert_ner_model")

import pandas as pd

rows = []

for entity, metrics in report.items():

    if isinstance(metrics, dict):

        rows.append({

            "Entity": entity,

            "Precision":
            metrics["precision"],

            "Recall":
            metrics["recall"],

            "F1":
            metrics["f1-score"],

            "Support":
            metrics["support"]
        })

entity_df = pd.DataFrame(rows)

entity_df

"""Visualize Per-Entity F1"""

import matplotlib.pyplot as plt

plot_df = entity_df[
    ~entity_df["Entity"].isin(
        ["micro avg",
         "macro avg",
         "weighted avg"]
    )
]

plot_df = plot_df.sort_values("F1")

plt.figure(figsize=(10,6))

plt.barh(
    plot_df["Entity"],
    plot_df["F1"]
)

plt.xlabel("F1 Score")
plt.title("DistilBERT NER Per-Entity F1")

plt.show()

"""Error Analysis"""

errors = []

for idx in range(len(true_labels)):

    if true_labels[idx] != true_predictions[idx]:

        errors.append({

            "Sample": idx,

            "True": true_labels[idx],

            "Predicted":
            true_predictions[idx]
        })

errors_df = pd.DataFrame(errors)

print(
    f"Number of Errors: {len(errors_df)}"
)

errors_df.head()

"""Confusion Analysis"""

from collections import Counter

confusions = Counter()

for true_seq, pred_seq in zip(
    true_labels,
    true_predictions
):

    for t, p in zip(
        true_seq,
        pred_seq
    ):

        if t != p:

            confusions[(t, p)] += 1

pd.DataFrame(

    confusions.most_common(20),

    columns=[
        "Confusion",
        "Count"
    ]
)

"""Training Curves"""

logging_steps=50

logs = trainer.state.log_history

history = pd.DataFrame(logs)

train_loss = history[
    history["loss"].notnull()
]

plt.figure(figsize=(8,5))

plt.plot(
    train_loss["step"],
    train_loss["loss"]
)

plt.xlabel("Steps")
plt.ylabel("Loss")

plt.title(
    "Training Loss"
)

plt.show()

"""Validation F1:"""

eval_f1 = history[
    history["eval_f1"].notnull()
]

plt.figure(figsize=(8,5))

plt.plot(
    eval_f1["epoch"],
    eval_f1["eval_f1"]
)

plt.xlabel("Epoch")
plt.ylabel("F1 Score")

plt.title(
    "Validation F1"
)

plt.show()

"""Latency Evaluation"""

import time
from transformers import pipeline

ner_pipe = pipeline(
    'ner',
    model=model,
    tokenizer=tokenizer
)

texts = [
    x["text"]
    for x in dev_hf[:500]
]

latencies = []

for text in texts:

    start = time.perf_counter()

    ner_pipe(text)

    end = time.perf_counter()

    latencies.append(
        (end-start)*1000
    )

print(
    "Mean:",
    np.mean(latencies)
)

print(
    "P95:",
    np.percentile(latencies,95)
)

print(
    "P99:",
    np.percentile(latencies,99)
)

"""Throughput"""

start = time.perf_counter()

for text in texts:

    ner_pipe(text)

end = time.perf_counter()

throughput = (
    len(texts)
    /
    (end-start)
)

print(
    f"Throughput: {throughput:.2f} req/sec"
)